require:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion:
    3.1
Style/Documentation:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Layout/SpaceAroundMethodCallOperator:
  Enabled: false
RSpec/LetSetup:
  Enabled: false
RSpec/ExampleLength:
  Enabled: false
RSpec/NamedSubject:
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: false
RSpec/SubjectStub:
  Enabled: true
  Exclude:
    - 'spec/feed_validator_spec.rb'

Style/EmptyElse:
  Enabled: true
  Exclude:
    - 'lib/feed_the_hungry/contracts/feed_contract.rb'

Naming/PredicateMethod:
  Enabled: true
  Exclude:
    - 'slices/api/mutations/remove_user.rb'
