require:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion:
    3.1
Style/Documentation:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Layout/SpaceAroundMethodCallOperator:
  Enabled: false
RSpec/LetSetup:
  Enabled: false
RSpec/ExampleLength:
  Enabled: false
RSpec/NamedSubject:
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: false

Style/EmptyElse:
  Enabled: true
  Exclude:
    - 'lib/feed_the_hungry/contracts/feed_contract.rb'
