version: '3.7'

services:
  app: &app
    build:
      context: .
    image: fth-backend:1.0.1

  backend: &backend
    <<: *app
    stdin_open: true
    tty: true
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
    environment:
      - RACK_ENV=${RACK_ENV:-development}
    env_file:
      - env/dev/web.env
    depends_on:
      - postgres

  web:
    <<: *backend
    command: bundle exec puma -C config/puma.rb
    ports:
      - 3000:3000
    depends_on:
      - sidekiq

  sidekiq:
    <<: *backend
    command: bundle exec sidekiq -e development -C config/sidekiq.yml -r ./config/boot.rb
    depends_on:
      - redis
      - postgres

  postgres:
    image: postgres:12-alpine
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    ports:
      - 5435:5432
    env_file: env/dev/db.env
    healthcheck:
      test: pg_isready -U app -h 127.0.0.1
      interval: 5s

  redis:
    image: redis:alpine
    logging:
      driver: "none"
    ports:
      - 6379:6379
    healthcheck:
      test: redis-cli ping
      interval: 1s
      timeout: 3s
      retries: 30

volumes:
  bundle:
  postgres_volume:
