:verbose: false
:concurrency: 20

:timeout: 600

:queues:
  - critical
  - default
  - low
  - mailers
  - scheduler

production:
  :concurrency: 20
staging:
  :concurrency: 20
development:
  :concurrency: 20

schedule:
  entry_importer_worker:
    cron: '*/30 * * * *'
    class: FeedTheHungry::Workers::Feeds::EntryImporterWorker
